// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG3_pRMCrdTuzC1dEuokbY6EuZfM4eyEY',
    appId: '1:75175098524:web:4394b615bb6203d0935559',
    messagingSenderId: '75175098524',
    projectId: 'people-for-people-5569a',
    authDomain: 'people-for-people-5569a.firebaseapp.com',
    storageBucket: 'people-for-people-5569a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEC7bDNNQMPJhJ2NEx3PiVD1TosPfyn0k',
    appId: '1:75175098524:android:067d68312c0493ff935559',
    messagingSenderId: '75175098524',
    projectId: 'people-for-people-5569a',
    storageBucket: 'people-for-people-5569a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdL312RF1SuSQJ19rEFA_2Q1mZahyLFrU',
    appId: '1:75175098524:ios:25c31efda93bdac3935559',
    messagingSenderId: '75175098524',
    projectId: 'people-for-people-5569a',
    storageBucket: 'people-for-people-5569a.firebasestorage.app',
    iosBundleId: 'com.example.people',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdL312RF1SuSQJ19rEFA_2Q1mZahyLFrU',
    appId: '1:75175098524:ios:25c31efda93bdac3935559',
    messagingSenderId: '75175098524',
    projectId: 'people-for-people-5569a',
    storageBucket: 'people-for-people-5569a.firebasestorage.app',
    iosBundleId: 'com.example.people',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG3_pRMCrdTuzC1dEuokbY6EuZfM4eyEY',
    appId: '1:75175098524:web:1e3bdf7c0abd8159935559',
    messagingSenderId: '75175098524',
    projectId: 'people-for-people-5569a',
    authDomain: 'people-for-people-5569a.firebaseapp.com',
    storageBucket: 'people-for-people-5569a.firebasestorage.app',
  );

}